theme: jekyll-theme-minimal
title: Adam Moller
description: Motivated data analyst who enjoys efficiently developing solutions to problems. Experienced in acquiring the knowledge and skills needed to make effective contributions.
